// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrWu5IUskv4fwmcZY7rawImcpcgggBUk',
    appId: '1:832343095246:web:d69c574435d00561f71d9f',
    messagingSenderId: '832343095246',
    projectId: 'app-blog-198a3',
    authDomain: 'app-blog-198a3.firebaseapp.com',
    storageBucket: 'app-blog-198a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSqadGQV_z31VK-w5w0pKUOmjWURRlp5A',
    appId: '1:832343095246:android:007eb6a4f2ad8a34f71d9f',
    messagingSenderId: '832343095246',
    projectId: 'app-blog-198a3',
    storageBucket: 'app-blog-198a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0hetjgTFrR5QIFrVSz_Yd2pdnrSgUmuU',
    appId: '1:832343095246:ios:f8dcb461a98cc077f71d9f',
    messagingSenderId: '832343095246',
    projectId: 'app-blog-198a3',
    storageBucket: 'app-blog-198a3.firebasestorage.app',
    iosBundleId: 'com.blogApp.blogAppSon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0hetjgTFrR5QIFrVSz_Yd2pdnrSgUmuU',
    appId: '1:832343095246:ios:f8dcb461a98cc077f71d9f',
    messagingSenderId: '832343095246',
    projectId: 'app-blog-198a3',
    storageBucket: 'app-blog-198a3.firebasestorage.app',
    iosBundleId: 'com.blogApp.blogAppSon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrWu5IUskv4fwmcZY7rawImcpcgggBUk',
    appId: '1:832343095246:web:eaf118070a32e3f4f71d9f',
    messagingSenderId: '832343095246',
    projectId: 'app-blog-198a3',
    authDomain: 'app-blog-198a3.firebaseapp.com',
    storageBucket: 'app-blog-198a3.firebasestorage.app',
  );
}
